Clean synced or unsynced duplicate caregivers
opensrp/opensrp-client-unicef-angola pull request #68
Opened 2021-10-29 07:55 UTC by hilpitome

2021-10-29 10:46 UTC, ekigamba requested changes

2021-10-29 10:46 UTC, ekigamba commented on opensrp-unicef-angola/build.gradle
> +    implementation('org.smartregister:opensrp-client-child:0.7.0-SNAPSHOT') {
:grimacing: This version change seems like a downgrade? Any reason?

2021-10-29 10:46 UTC, ekigamba commented on opensrp-unicef-angola/src/main/java/org/smartregister/unicefangola/presenter/NavigationPresenter.java
> +import com.google.firebase.crashlytics.FirebaseCrashlytics;
Different issue: I just checked the Firebase console and we still don't have a single log for the Angola app. I think it would be nice to aim to have this in so that we can easily get error logs in future

2021-10-29 10:46 UTC, ekigamba commented on opensrp-unicef-angola/src/main/java/org/smartregister/unicefangola/activity/ChildRegisterActivity.java
> + package org.smartregister.unicefangola.activity;
Small issue: Revert this

2021-10-29 10:46 UTC, ekigamba commented on opensrp-unicef-angola/src/main/java/org/smartregister/unicefangola/util/DataCleanUpUtils.java
Looks good. I was not able to check/test the query

2021-10-29 11:22 UTC, hilpitome commented on opensrp-unicef-angola/build.gradle
> +    implementation('org.smartregister:opensrp-client-child:0.7.0-SNAPSHOT') {
For some reason I am not able to download that version on my end.

2021-11-23 06:22 UTC, ndegwamartin commented on opensrp-unicef-angola/build.gradle
> +    implementation('org.smartregister:opensrp-client-child:0.7.0-SNAPSHOT') {
VLOGS was for Verbose Logs, the version used for troubleshooting on the field

2022-07-06 07:43 UTC, hilpitome commented on opensrp-unicef-angola/src/main/java/org/smartregister/unicefangola/presenter/NavigationPresenter.java
> +import com.google.firebase.crashlytics.FirebaseCrashlytics;
This was being done in this PR#[62](https://github.com/opensrp/opensrp-client-unicef-angola/pull/62)

2022-07-06 07:43 UTC, merged